Refactored networks.py into networks module
cnellington/Contextualized pull request #78
Opened 2022-04-18 20:32 UTC by cnellington

Resolves #63

2022-04-18 21:24 UTC, blengerich commented on contextualized/networks/__init__.py
> +from contextualized.regression.datasets import UnivariateDataset, MultitaskUnivariateDataset
If these are used for both regression and networks, should they be in contextualized.regression?

2022-04-18 21:25 UTC, blengerich commented on contextualized/networks/__init__.py
> +from contextualized.regression.losses import MSE
If this is used for both regression and networks, should it be in contextualized.regression?

2022-04-18 21:25 UTC, blengerich commented on contextualized/networks/__init__.py
> +from contextualized.regression.regularizers import *
If this is used for both regression and networks, should it be in contextualized.regression?

2022-04-18 21:28 UTC, blengerich commented on contextualized/networks/trainers.py
> +class CorrelationTrainer(RegressionTrainer):
Is correlation a network-specific function? Should we have a CorrelationTrainer in contextualized.regression.trainers?

2022-04-18 21:29 UTC, blengerich commented on contextualized/networks/lightning_modules.py
> +    Using umultitask nivariate contextualized regression to estimate Pearson's correlation
spelling

2022-04-18 21:29 UTC, blengerich requested changes
Some questions about placement in modules

2022-04-20 18:41 UTC, cnellington commented
Correlation is a specific use case of univariate regression, so I agree it makes more sense to have a general correlation class / trainer in the regression module. I'll add what we have now to regression and make an issue to add the general ContextualizedCorrelation(C, X, Y) in the future.

2022-04-21 17:19 UTC, blengerich approved these changes
LGTM

2022-04-21 18:02 UTC, merged